version: '3'

services:
  api:
    depends_on:
      - db
    image: blog_sample
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  
  db:
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: blog_production
      MYSQL_USER: root

volumes:
  db_data: